version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    hostname: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=portsdb
    ports:
      - '5432:5432'
    volumes:
#      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  ports-service:
    build: .
    depends_on:
      db:
        condition: service_healthy
    image: ports-service:latest
    ports:
      - '8080:8080'
volumes:
  db:
    driver: local